stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
    outs:
      - data/raw_data
    params:
      - data_ingestion.test_size

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - data/raw_data
      - src/data/data_preprocessing.py
    outs:
      - data/preprocessed_data


  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - data/preprocessed_data
      - src/features/feature_engineering.py
    outs:
      - data/features_data
    params:
      - feature_engineering.max_features

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/features_data
    - src/model/model_building.py
    outs:
    - models/model_tfidf.pkl
    params:
    - model_building.n_estimators
  
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - models/model_tfidf.pkl
      - src/model/model_evaluation.py
      - models/model_tfidf.pkl               
    metrics:
      - metrics.json:
          cache: false

